### ISSUE TITLE
Write into Value List

### ISSUE THREAD

**Issue by mech** [ginjo/rfm#32]
Is it possible to write into value list item? Is such an API even possible?

**Comment by ginjo** [comment]
@mech, I don't think there is an api for writing to FM native value lists. I thought it could be done with a script, but I can't find any such FM script step.

However, you can create a table-based value list in Filemaker. Then you can manipulate the value list just like any other table. And as far as ruby goes, your "value list" is just another array.

**Comment by mech** [comment]
Good idea on table-based value list. What you mean is it is just another table layout right. Totally by-pass the Value List functionality in FM and just make it a table.

**Comment by ginjo** [comment]
Yes, as far as Rfm is concerned, it is just another table pulled from a layout. But you can have it both ways, since filemaker has an option to define a value list by any table. So if you update that value-list-table with Ruby, the FM value list in Filemaker would also be updated for FM-client users.

**Comment by mech** [comment]
Got it.. tks alot :smile:
