### ISSUE TITLE
Is it possible to return only selected fields rather than the entire record?

### ISSUE THREAD

**Issue by dmichael** [ginjo/rfm#34]
I was curious what, if any, the syntax would be for returning an array of only a specific field rather than bogging the server down with entire records.

**Comment by ginjo** [comment]
There is a way to control what fields are returned, but it's not in Ruby, unfortunately. Filemaker server returns all fields on the layout that you are querying against.

One work-around is that you can choose a different layout for the response vs the query. That part _can_ be done in Ruby, by using Rfm's ```:response_layout``` query option.

    class Reservation < Rfm::Base
      config :layout => 'reservation_layout'
    end

    Reservation.find({:login => 'bill'}, :response_layout => 'other_reservation_layout')

You just need to make sure that the response layout is of the same table-occurrence as your main query layout, so that you get the correct result set returned.

**Comment by dmichael** [comment]
Great - thanks for the feedback!
